[build]
    command = "npm run build"
    commandOrigin = "config"
    publish = ".next"
    publishOrigin = "config"

[[plugins]]
    inputs = {}
    origin = "config"
    package = "@netlify/plugin-nextjs"